# Generated by Django 6.0.2 on 2026-02-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=80)),
                ('short_desc', models.TextField(help_text='Katalog kartochkasida ko‘rinadi')),
                ('full_desc', models.TextField(help_text='Sharh sahifasida batafsil chiqadi')),
                ('slug', models.SlugField(unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
